import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About - Better Marque® Embrace Uniqueness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
