import type { Metadata } from "next";
import { Footer } from "@/components";
import "../styles/globals.scss";


export const metadata: Metadata = {
  title: "Better Marque - Branding Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
