import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Get in touch - Better Marque",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <body>
        {children}
      </body>

  );
}
