import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.scss";

const sfproregular = localFont(options: {
  
})


export const metadata: Metadata = {
  title: "Better Marque - Branding Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        {children}
      </body>
    </html>
  );
}
